apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-profile-hpa
  namespace: vijay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profile-service-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

